#!/bin/bash
CONFDIR=$HOME/.config/twitch-py
EXEC=/usr/local/bin/twitch-py
BIN=https://github.com/RaeedAhmed/twitch-py/releases/latest/download/twitch-py.bin
echo "Setting up static files..."
if [ -d "$CONFDIR" ]; then
    rm -r $CONFDIR
fi
mkdir $CONFDIR
cp -R twitch-py/config $CONFDIR
cp -R twitch-py/views $CONFDIR

while getopts p option
do
    case "${option}"
    in
    p) exit 1
    esac
done

if [ -f "$EXEC" ]; then
    echo "Removing past installation..."
    sudo rm $EXEC
else
    echo "No past installation..."
fi

echo "[3] Downloading binary"
sudo wget -q --show-progress -O $EXEC $BIN || sudo curl -sL $BIN | sudo tee $EXEC >/dev/null
sudo chmod +x $EXEC
