title = "twitch-py settings"

[Linux]
multi = false
app = "mpv"
args = "--hwdec=auto --screen=1 --fs --keep-open=yes"

[Windows]
multi = false
app = "C:\\Program\\Files\\VideoLAN\\VLC\\vlc.exe"
args = ""

[Darwin]
multi = false
app = ""
args = ""
